### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by ashvalejohn** [ashvalejohn/flex-project#37]
At `/` => If user is logged in, redirect to `/log`, otherwise redirect to `/login`.

**Comment by ashvalejohn** [comment]
- redirect to `/login` on logout

**Comment by nwilliams770** [comment]
- [x] Upon login, user is directed to log-poke
- [x] upon signup, user is directed to settings
- [x] upon logging poke (successfully), user is directed to poke-log
- [x] "/" will always redirect to log-poke
